detectors:
  InstanceVariableAssumption:
    exclude:
      - "Tramway::BaseForm"
      - "UsersController"
  BooleanParameter:
    exclude:
      - "Tramway::BaseForm"
      - "Tailwinds::Form::MultiselectComponent"
  DataClump:
    exclude:
      - "Tailwinds::Form::Builder"
  LongParameterList:
    max_params: 5

directories:
  "spec/dummy/app/controllers":
    IrresponsibleModule:
      enabled: false
  "spec/dummy/app/decorators":
    IrresponsibleModule:
      enabled: false
  "spec/dummy/db/migrate/":
    FeatureEnvy: 
      enabled: false
    IrresponsibleModule:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  "lib/tramway/helpers":
    UtilityFunction:
      enabled: false
  "lib/tramway/utils":
    UtilityFunction:
      enabled: false
