detectors:
  InstanceVariableAssumption:
    exclude:
      - "Tramway::BaseForm"
  BooleanParameter:
    exclude:
      - "Tramway::BaseForm"
  DataClump:
    exclude:
      - "Tailwinds::Form::Builder"

directories:
  "spec/dummy/db/migrate/":
    FeatureEnvy: 
      enabled: false
    IrresponsibleModule:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  "lib/tramway/helpers":
    UtilityFunction:
      enabled: false
  "lib/tramway/utils":
    UtilityFunction:
      enabled: false
