plugins:
  - rubocop-rspec
  - rubocop-rails

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/migrate/**

Metrics/AbcSize:
  Exclude:
    - lib/generators/**/*.rb

RSpec/MultipleExpectations:
  Max: 4

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/tramway/helpers/views_helpers/*_spec.rb

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/ItBlockParameter:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
