require: rubocop-rails

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.2
