plugins:
  - rubocop-rspec
  - rubocop-rails

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/migrate/**

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/ItBlockParameter:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
