Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/MissingRespondToMissing:
  Exclude:
    - lib/tramway/base_form.rb

AllCops:
  TargetRubyVersion: 3.2
