require:
  - rubocop-rspec
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 12
  Exclude:
    - spec/dummy/db/migrate/*.rb
    - app/forms/tramway/extendable_forms_helpers/class_builder.rb
Metrics/MethodLength:
  Max: 13
  Include:
    - app/decorators/tramway/associations/class_helper.rb
Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/decorators/tramway/application_decorator_spec.rb
Metrics/BlockLength:
  Enabled: false
  Include:
    - spec/
Metrics/AbcSize:
  Max: 18
  Exclude:
    - spec/dummy/db/migrate/*.rb
    - app/forms/tramway/extendable_forms_helpers/class_builder.rb
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - spec/dummy/config/application.rb
    - lib/tramway/version.rb
    - lib/tramway/generators.rb
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Style/MixinUsage:
  Exclude:
    - bin/*
    - spec/dummy/bin/*
Metrics/PerceivedComplexity:
  Max: 10
Style/ClassVars:
  Exclude:
    - app/forms/tramway/extended_application_form.rb
    - app/forms/tramway/application_form.rb
    - app/decorators/tramway/associations/class_helper.rb
    - lib/tramway.rb
    - spec/forms/tramway/application_form_spec.rb
Naming/MethodParameterName:
  Exclude:
    - app/decorators/tramway/associations/class_helper.rb
Style/MultilineBlockChain:
  Enabled: false
Style/GuardClause:
  Exclude:
    - lib/tramway/generators/model_generator.rb # rubocop bug
RSpec/DescribeClass:
  Exclude:
    - spec/test_env_spec.rb
    - spec/features/**/*.rb
RSpec/NestedGroups:
  Max: 4
RSpec/ExampleLength:
  Max: 10
AllCops:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/seeds.rb
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - spec/dummy/Rakefile
  Exclude:
    - spec/dummy/**/*.rb
  TargetRubyVersion: 2.7
