require: rubocop-rails
require: rubocop-rspec

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false
  
Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
