module.exports = {
  safelist: [
    // === Navbar ===
    'ml-4',
    'text-white',
    'md:flex',
    'transform',
    'left-1/2',
    '-translate-x-1/2',
    'md:left-auto',
    'md:translate-x-0',
    'border-white',
    'h-screen',
    'w-screen',
    'z-50',
    'inset-0',
    'top-4',
    'right-6',
    'text-4xl',
    'transition-transform',
    '-translate-x-full',
    'duration-300',
    'space-y-3',
    'md:justify-between',
    'pt-16',
    'min-h-8',
    'bg-zinc-950',
    'bg-zinc-950/95',
    'bg-zinc-950/80',
    'bg-zinc-900',
    'bg-zinc-800',
    'bg-zinc-900/80',
    'border-zinc-800',
    'text-zinc-50',
    'text-zinc-100',
    'text-zinc-400',
    'text-zinc-500',
    'hover:bg-zinc-800',
    'hover:bg-zinc-900',
    'hover:text-zinc-50',
    'focus-visible:ring-zinc-400',
    'focus-visible:ring-offset-zinc-950',
    'supports-[backdrop-filter]:bg-zinc-950/80',
    'backdrop-blur',
    'shadow-lg',
    'shadow-sm',
    'w-full',
    'text-base',
    'text-sm',
    'rounded-md',
    'border-b',
    'border-r',
    'border-t',
    'border',
    'gap-4',
    'gap-1',
    'gap-2',
    'grid-cols-1',
    'grid',
    'px-4',
    'py-3',
    'py-4',
    'py-6',
    'p-2',
    'inset-0',
    'top-4',
    'right-4',
    'flex-col',
    'items-center',
    'justify-between',
    'justify-center',
    'transition-colors',
    'rounded-md',
    'truncate',
    'rounded-b-none',
    'overflow-x-hidden',
    'cursor-not-allowed',
    'mx-auto',
    'my-4',
    'h-8',
    'w-8',
    'disabled:cursor-not-allowed',

    // === Entities Index Page ===
    'md:mt-8',

    // === Chat components ===
    'mt-6',
    'mt-3',
    'max-h-full',
    'rounded-2xl',
    'rounded-tl-md',
    'rounded-tr-md',
    'bg-white',
    'bg-gray-50',
    'bg-gray-800/60',
    'bg-blue-600',
    'bg-blue-500',
    'shadow-sm',
    'border-t',
    'border-gray-200',
    'border-gray-300',
    'border-gray-600',
    'border-gray-700',
    'bg-gray-800',
    'bg-gray-900',
    'hover:bg-blue-400',
    'text-gray-100',
    'text-gray-400',
    'text-blue-400',
    'placeholder:text-gray-400',
    'focus:border-gray-300',
    'focus:border-blue-400',
    'focus:border-blue-500',
    'focus:ring-blue-500/30',
    'focus:ring-blue-500',
    'ring-gray-700',
    'ring-1',
    'h-8',
    'flex-1',
    'gap-2',
    'gap-3',
    'items-start',
    'items-end',
    'max-w-lg',
    'overflow-hidden',
    'overflow-y-auto',
    'my-4',
    'p-6',
    'pb-1',
    'py-3',
    'ring-1',
    'space-y-4',
    'text-right',
    'text-sm',
    'text-gray-900',
    'text-blue-100/90',
    'text-red-200',
    'underline',
    'break-all',
    'animate-spin',
    'placeholder:text-gray-400',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-blue-200',
    'disabled:bg-gray-100',
    'hover:bg-blue-500',
    'bg-blue-600',
    'bg-gray-800/60',
    'min-h-0',
    'min-w-0',
    'flex-1',
    'overflow-y-auto',
    'overflow-hidden',
    'shrink-0',
    'md:p-4',
    'md:p-6',
    'p-2',
    'md:gap-1',
    'md:space-y-4',
    'space-y-2',
    'md:pt-2',
    'md:rounded-xl',
    'rounded-t-xl',
    'md:rounded-full',
    'rounded-bl-2xl',
    'md:border',
    'md:gap-1',
    'hover:underline',
    'marker:hidden',
    'list-none',

    // === Custom table layout utilities ===
    'div-table',
    'div-table-row',
    'div-table-cell',
    'sm:text-base',
    'last:border-b-0',
    'md:block',
    'first:block',
    'rounded-t-xl',
    'border-zinc-800',
    'bg-zinc-950',
    'bg-zinc-900',
    'text-zinc-100',
    'text-zinc-400',
    'hover:bg-zinc-900',
    'border-b',
    'border-r',
    'grid-cols-1',
    'gap-4',
    'px-6',
    'py-4',
    'font-medium',
    'w-full',

    // === Table row preview panel ===
    'bottom-0',
    'left-0',
    'right-0',
    'h-1/2',
    'bg-gray-100',
    'animate-roll-up',
    'hover:text-gray-700',
    'pt-4',
    'md:hidden',

    // === Title Component ===
    'md:text-4xl',

    // === Visibility and typography helpers ===
    'hidden',
    'text-xl',
    'font-bold',

    // === Button base shell ===
    'inline-flex',
    'rounded-md',
    'font-medium',
    'ring-offset-background',
    'transition-colors',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-ring',
    'focus-visible:ring-offset-2',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    'h-10',

    'hover:bg-zinc-250',
    'bg-zinc-50',
    'text-zinc-950',

    'hover:bg-green-900',
    'bg-green-900/30',
    'text-green-400',

    'hover:bg-red-900',
    'bg-red-900/30',
    'text-red-400',

    'hover:bg-gray-900',
    'bg-gray-900/30',
    'text-gray-400',

    'hover:bg-blue-900',
    'bg-blue-900/30',
    'text-blue-400',

    'hover:bg-zinc-900',
    'bg-zinc-900/30',
    'text-zinc-400',

    'hover:bg-orange-900',
    'bg-orange-900/30',
    'text-orange-400',

    'hover:bg-violet-900',
    'bg-violet-900/30',
    'text-violet-400',

    'hover:bg-indigo-900',
    'bg-indigo-900/30',
    'text-indigo-400',

    'hover:bg-yellow-900',
    'bg-yellow-900/30',
    'text-yellow-400',

    // === Grid templates used for configurable layouts ===
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'grid-cols-7',
    'grid-cols-8',
    'grid-cols-9',
    'grid-cols-10',
    'md:grid-cols-1',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'md:grid-cols-5',
    'md:grid-cols-6',
    'md:grid-cols-7',
    'md:grid-cols-8',
    'md:grid-cols-9',
    'md:grid-cols-10',

    // === Page container and alignment helpers ===
    'container',
    'mx-auto',
    'align-center',
    'justify-center',
    'min-h-dvh',
    'bg-zinc-950',
    'text-zinc-50',

    // === Flexbox layout utilities ===
    'flex',
    'flex-col',
    'flex-wrap',
    'flex-row-reverse',
    'flex-auto',
    'flex-initial',
    'justify-between',
    'justify-end',
    'space-x-1',
    'items-center',

    // === Responsive visibility helpers ===
    'sm:hidden',
    'sm:flex',

    // === Sizing utilities ===
    'w-full',
    'w-fit',
    'w-8',
    'min-w-96',
    'max-w-full',

    // === Spacing utilities ===
    'p-4',
    'px-6',
    'px-4',
    'px-3',
    'px-2',
    'py-4',
    'py-2',
    'py-1',
    'mb-4',
    'mb-2',
    'mt-8',
    'mt-2',

    // === Pagination styles ===
    'hover:bg-gray-300',
    'gap-x-1',

    // === Dark mode pagination styles ===
    'bg-gray-900',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'hover:text-gray-600',
    'placeholder-gray-400',
    'placeholder-gray-500',

    // === Button and badge helpers ===
    'rounded',
    'rounded-full',
    'rounded-xl',
    'font-medium',
    'font-semibold',
    'text-xs',
    'whitespace-nowrap',
    'h-fit',
    'gap-1',
    'h-10',
    'shadow-md',
    'shadow-inner',
    'shadow-lg',
    'h-12',

    // === Shadcn UI button styles ===
    'bg-green-600',
    'hover:bg-green-400',
    'text-green-800',

    // === Button Disabled state ===
    'bg-gray-200',
    'text-gray-100',
    'text-gray-200',
    'text-gray-300',
    'text-gray-400',
    'text-gray-500',
    'text-gray-700',
    'text-gray-800',
    'text-blue-800',
    'text-zinc-800',
    'text-green-800',
    'text-orange-800',
    'text-red-800',
    'text-violet-800',
    'text-indigo-800',
    'text-yellow-800',
    'text-teal-800',

    // === Form state helpers ===
    'disabled:text-gray-400',
    'disabled:cursor-not-allowed',
    'disabled:bg-gray-200',
    'disabled:text-gray-500',
    'focus:ring-gray-300',
    'focus:ring-gray-600',
    'ring-gray-200',
    'ring-gray-700',
    'border-gray-200',
    'border-gray-300',
    'border-gray-700',
    'hover:border-gray-300',
    'border-teal-200',
    'border-teal-700',

    // === Form size helpers ===
    'px-5',
    'py-3',

    // === Form styles ===
    'list-disc',
    'list-inside',
    'pl-6',
    'p-4',
    'border-red-600',
    'bg-red-100',
    'text-red-800',
    'space-x-2',
    'h-5',
    'w-5',
    'rounded-full',
    'mb-0',

    // === Tramway select dropdown positioning ===
    'absolute',
    'relative',
    'shadow',
    'z-40',
    'max-h-select',
    'overflow-y-auto',
    'cursor-pointer',
    'border-gray-600',
    'text-gray-100',

    // === Tramway select option styling ===
    'border-b',
    'border',
    'border-l',
    'border-l-2',
    'border-transparent',
    'bg-teal-100',
    'bg-transparent',
    'leading-6',
    'leading-none',
    'appearance-none',
    'outline-none',
    'h-full',
    'm-1',
    'p-1',
    'p-2',
    'p-3',
    'rounded-b-xl',
    'hover:bg-gray-800',
    'border-gray-700',
    'h-15',
    'h-12',
    'h-10',
    'min-w-2',
    'min-h-2',
    'min-w-4',
    'min-h-4',
    'min-w-6',
    'min-h-6',
    'px-2',
    'py-1',
    'flex-nowrap',
    'overflow-x-auto',
    'focus:outline-none',
    'focus:ring-0',

    // === Flash message styles ===
    'fixed',
    'right-4',
    'z-50',
    'space-y-2',
    'flash',
    'opacity-100',
    'text-white',
    'px-4',
    'py-2',
    'rounded',
    'shadow',
    'text-black',
    'pointer-events-none'
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        attention: {
          DEFAULT: "var(--yellow-50)",
          foreground: "hsl(var(--attention-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", ...defaultTheme.fontFamily.sans],
        sans: ["Inter var", ...defaultTheme.fontFamily.sans],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    },
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/container-queries"),
  ],
}
