module.exports = {
  safelist: [
    // === Navbar ===
    'ml-4',
    'text-white',
    'md:flex',
    
    // === Custom table layout utilities ===
    'div-table',
    'div-table-row',
    'div-table-cell',
    'sm:text-base',
    'last:border-b-0',
    'md:block',
    'first:block',
    'rounded-t-xl',

    // === Visibility and typography helpers ===
    'hidden',
    'xl:hidden',
    'text-xl',
    'text-4xl',
    'font-bold',
    'text-right',

    // === Grid templates used for configurable layouts ===
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'grid-cols-7',
    'grid-cols-8',
    'grid-cols-9',
    'grid-cols-10',
    'md:grid-cols-1',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'md:grid-cols-5',
    'md:grid-cols-6',
    'md:grid-cols-7',
    'md:grid-cols-8',
    'md:grid-cols-9',
    'md:grid-cols-10',

    // === Page container and alignment helpers ===
    'container',
    'mx-auto',
    'align-center',
    'justify-center',

    // === Flexbox layout utilities ===
    'flex',
    'flex-col',
    'flex-wrap',
    'flex-row-reverse',
    'flex-auto',
    'flex-initial',
    'justify-between',
    'justify-end',
    'space-x-1',
    'items-center',

    // === Responsive visibility helpers ===
    'sm:hidden',
    'sm:flex',

    // === Sizing utilities ===
    'w-2/3',
    'w-full',
    'w-fit',
    'w-8',
    'min-w-96',
    'max-w-full',

    // === Spacing utilities ===
    'p-4',
    'px-6',
    'px-4',
    'px-3',
    'px-2',
    'py-8',
    'py-4',
    'py-2',
    'py-1',
    'mb-2',
    'mt-8',
    'mt-2',

    // === Pagination styles ===
    'bg-white',
    'rounded-md',
    'hover:bg-purple-100',
    'hover:bg-gray-100',
    'hover:bg-gray-300',
    'hover:text-gray-800',

    // === Dark mode pagination styles ===
    'text-white',
    'bg-gray-800',
    'hover:bg-gray-700',
    'bg-gray-900',
    'bg-gray-700',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-200',
    'text-gray-300',
    'hover:text-gray-400',
    'hover:text-gray-600',
    'placeholder-gray-400',
    'placeholder-gray-500',

    // === Button and badge helpers ===
    'bg-purple-700',
    'rounded',
    'rounded-full',
    'rounded-t',
    'rounded-xl',
    'font-medium',
    'font-normal',
    'font-semibold',
    'text-xs',
    'whitespace-nowrap',
    'h-fit',
    'gap-1',
    'h-10',
    'shadow-md',
    'shadow-inner',
    'shadow-lg',

    // === Button color presets ===
    'bg-gray-500',
    'bg-gray-600',
    'hover:bg-gray-700',
    'hover:bg-gray-800',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-700',
    'bg-gray-800',
    'bg-gray-900',
    'hover:bg-gray-200',
    'hover:bg-gray-300',

    'bg-blue-500',
    'bg-blue-600',
    'hover:bg-blue-700',
    'hover:bg-blue-800',
    'bg-blue-100',
    'bg-blue-200',
    'bg-blue-800',
    'bg-blue-900',
    'hover:bg-blue-200',
    'hover:bg-blue-300',

    'bg-zinc-500',
    'bg-zinc-600',
    'hover:bg-zinc-700',
    'hover:bg-zinc-800',
    'bg-zinc-100',
    'bg-zinc-200',
    'bg-zinc-700',
    'hover:bg-zinc-300',

    'bg-green-400',
    'bg-green-500',
    'bg-green-600',
    'hover:bg-green-700',
    'hover:bg-green-800',
    'bg-green-100',
    'bg-green-200',
    'bg-green-700',
    'hover:bg-green-300',

    'bg-orange-500',
    'bg-orange-600',
    'hover:bg-orange-700',
    'hover:bg-orange-800',
    'bg-orange-100',
    'bg-orange-200',
    'bg-orange-700',
    'bg-orange-800',
    'hover:bg-orange-300',

    'bg-red-500',
    'bg-red-600',
    'bg-red-700',
    'hover:bg-red-700',
    'hover:bg-red-800',
    'bg-red-100',
    'bg-red-200',
    'bg-red-800',
    'bg-red-900',
    'hover:bg-red-200',
    'hover:bg-red-300',

    'bg-violet-500',
    'bg-violet-600',
    'hover:bg-violet-700',
    'hover:bg-violet-800',
    'bg-violet-100',
    'bg-violet-200',
    'bg-violet-700',
    'hover:bg-violet-300',

    'bg-indigo-500',
    'bg-indigo-600',
    'hover:bg-indigo-700',
    'hover:bg-indigo-800',
    'bg-indigo-100',
    'bg-indigo-200',
    'bg-indigo-700',
    'hover:bg-indigo-300',

    'bg-yellow-500',
    'bg-yellow-600',
    'hover:bg-yellow-700',
    'hover:bg-yellow-800',
    'bg-yellow-100',
    'bg-yellow-200',
    'bg-yellow-700',
    'hover:bg-yellow-300',
    'bg-teal-100',
    'bg-teal-200',
    'bg-teal-900',

    // === Button Disabled state ===
    'bg-gray-400',
    'bg-gray-200',
    'text-gray-400',
    'text-gray-500',
    'text-gray-100',
    'text-gray-700',
    'text-gray-800',
    'text-gray-200',
    'text-gray-300',
    'text-blue-800',
    'text-blue-100',
    'text-zinc-800',
    'text-zinc-100',
    'text-green-800',
    'text-green-100',
    'text-orange-800',
    'text-orange-100',
    'text-red-800',
    'text-red-100',
    'text-violet-800',
    'text-violet-100',
    'text-indigo-800',
    'text-indigo-100',
    'text-yellow-800',
    'text-yellow-100',
    'text-teal-100',
    'text-teal-800',

    // === Form state helpers ===
    'disabled:bg-gray-100',
    'disabled:text-gray-400',
    'disabled:cursor-not-allowed',
    'disabled:bg-gray-200',
    'disabled:text-gray-500',
    'mb-4',
    'bg-red-500',
    'focus:ring-gray-300',
    'focus:ring-gray-600',
    'ring-gray-200',
    'ring-gray-700',
    'border-gray-200',
    'border-gray-300',
    'border-gray-700',
    'hover:border-gray-300',
    'border-teal-200',
    'border-teal-700',

    // === Dark mode helpers ===
    'dark:bg-gray-700',
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:bg-blue-700',
    'dark:bg-blue-800',
    'dark:bg-blue-900',
    'dark:bg-zinc-700',
    'dark:bg-green-700',
    'dark:bg-orange-700',
    'dark:bg-orange-800',
    'dark:bg-red-700',
    'dark:bg-red-800',
    'dark:bg-red-900',
    'dark:bg-violet-700',
    'dark:bg-indigo-700',
    'dark:bg-yellow-700',
    'dark:bg-teal-900',
    'dark:text-gray-100',
    'dark:text-gray-200',
    'dark:text-gray-300',
    'dark:text-gray-400',
    'dark:text-gray-500',
    'dark:text-blue-100',
    'dark:text-zinc-100',
    'dark:text-green-100',
    'dark:text-orange-100',
    'dark:text-red-100',
    'dark:text-violet-100',
    'dark:text-indigo-100',
    'dark:text-yellow-100',
    'dark:text-teal-100',
    'dark:border-gray-700',
    'dark:border-teal-700',
    'dark:ring-gray-700',
    'dark:placeholder-gray-500',
    'dark:focus:ring-gray-600',
    'dark:focus:ring-red-700',
    'dark:disabled:bg-gray-800',
    'dark:disabled:text-gray-500',
    'dark:hover:bg-gray-600',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-gray-800',
    'dark:hover:bg-blue-600',
    'dark:hover:bg-blue-800',
    'dark:hover:bg-red-600',
    'dark:hover:bg-red-800',
    'dark:hover:bg-orange-600',
    'dark:hover:bg-orange-700',
    'dark:hover:bg-violet-600',
    'dark:hover:bg-violet-700',
    'dark:hover:bg-indigo-600',
    'dark:hover:bg-green-600',
    'dark:hover:bg-yellow-600',
    'dark:hover:bg-zinc-600',
    'dark:hover:text-gray-300'

    // === Multiselect dropdown positioning ===
    'absolute',
    'relative',
    'shadow',
    'top-11',
    'z-40',
    'left-0',
    'max-h-select',
    'overflow-y-auto',
    'cursor-pointer',
    'border-gray-600',
    'text-gray-100',

    // === Multiselect option styling ===
    'border-b',
    'border',
    'border-l',
    'border-l-2',
    'border-transparent',
    'border-teal-300',
    'hover:border-teal-100',
    'bg-teal-100',
    'bg-transparent',
    'text-teal-700',
    'leading-6',
    'leading-none',
    'appearance-none',
    'outline-none',
    'h-full',
    'm-1',
    'hover:bg-teal-100',

    // === Flash message styles ===
    'fixed',
    'top-6',
    'right-4',
    'z-50',
    'space-y-2',
    'flash',
    'opacity-100',
    'bg-green-700',
    'text-white',
    'px-4',
    'py-2',
    'rounded',
    'shadow',
    'bg-yellow-700',
    'text-black'
  ],
}
