name: Abstract Tests

on: [workflow_call]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build --abort-on-container-exit"
          down-flags: "--volumes"
