name: Tests

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  release:
    types: [created]
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    uses: ./.github/workflows/rspec.yml
